// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface DeleteCourseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.DeleteCourseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string course_id = 1;</code>
   * @return The courseId.
   */
  java.lang.String getCourseId();
  /**
   * <code>string course_id = 1;</code>
   * @return The bytes for courseId.
   */
  com.google.protobuf.ByteString
      getCourseIdBytes();
}
