// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.Empty)
    com.google.protobuf.MessageOrBuilder {
}
