// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   * @return The studentId.
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   * @return The bytes for studentId.
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();

  /**
   * <code>repeated string course_id = 2;</code>
   * @return A list containing the courseId.
   */
  java.util.List<java.lang.String>
      getCourseIdList();
  /**
   * <code>repeated string course_id = 2;</code>
   * @return The count of courseId.
   */
  int getCourseIdCount();
  /**
   * <code>repeated string course_id = 2;</code>
   * @param index The index of the element to return.
   * @return The courseId at the given index.
   */
  java.lang.String getCourseId(int index);
  /**
   * <code>repeated string course_id = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the courseId at the given index.
   */
  com.google.protobuf.ByteString
      getCourseIdBytes(int index);
}
