// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   * @return The studentId.
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   * @return The bytes for studentId.
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();

  /**
   * <code>string last_name = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string first_name = 3;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 3;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string department = 4;</code>
   * @return The department.
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 4;</code>
   * @return The bytes for department.
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();

  /**
   * <code>repeated string course_id = 5;</code>
   * @return A list containing the courseId.
   */
  java.util.List<java.lang.String>
      getCourseIdList();
  /**
   * <code>repeated string course_id = 5;</code>
   * @return The count of courseId.
   */
  int getCourseIdCount();
  /**
   * <code>repeated string course_id = 5;</code>
   * @param index The index of the element to return.
   * @return The courseId at the given index.
   */
  java.lang.String getCourseId(int index);
  /**
   * <code>repeated string course_id = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the courseId at the given index.
   */
  com.google.protobuf.ByteString
      getCourseIdBytes(int index);
}
