// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   * @return The studentId.
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   * @return The bytes for studentId.
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();

  /**
   * <code>string last_name = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string first_name = 3;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 3;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>repeated .university.Course courses = 4;</code>
   */
  java.util.List<com.cluper.course_registration.Course> 
      getCoursesList();
  /**
   * <code>repeated .university.Course courses = 4;</code>
   */
  com.cluper.course_registration.Course getCourses(int index);
  /**
   * <code>repeated .university.Course courses = 4;</code>
   */
  int getCoursesCount();
  /**
   * <code>repeated .university.Course courses = 4;</code>
   */
  java.util.List<? extends com.cluper.course_registration.CourseOrBuilder> 
      getCoursesOrBuilderList();
  /**
   * <code>repeated .university.Course courses = 4;</code>
   */
  com.cluper.course_registration.CourseOrBuilder getCoursesOrBuilder(
      int index);
}
