// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface AddCourseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.AddCourseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.university.Course course = 1;</code>
   * @return Whether the course field is set.
   */
  boolean hasCourse();
  /**
   * <code>.university.Course course = 1;</code>
   * @return The course.
   */
  com.cluper.course_registration.Course getCourse();
  /**
   * <code>.university.Course course = 1;</code>
   */
  com.cluper.course_registration.CourseOrBuilder getCourseOrBuilder();
}
