// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface AddStudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.AddStudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.university.Student student = 1;</code>
   * @return Whether the student field is set.
   */
  boolean hasStudent();
  /**
   * <code>.university.Student student = 1;</code>
   * @return The student.
   */
  com.cluper.course_registration.Student getStudent();
  /**
   * <code>.university.Student student = 1;</code>
   */
  com.cluper.course_registration.StudentOrBuilder getStudentOrBuilder();
}
