// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

/**
 * Protobuf type {@code university.Course}
 */
public  final class Course extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:university.Course)
    CourseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Course.newBuilder() to construct.
  private Course(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Course() {
    courseId_ = "";
    profName_ = "";
    courseName_ = "";
    prerequisite_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Course();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Course(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            courseId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            profName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            courseName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              prerequisite_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            prerequisite_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        prerequisite_ = prerequisite_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cluper.course_registration.University.internal_static_university_Course_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cluper.course_registration.University.internal_static_university_Course_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cluper.course_registration.Course.class, com.cluper.course_registration.Course.Builder.class);
  }

  public static final int COURSE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object courseId_;
  /**
   * <code>string course_id = 1;</code>
   * @return The courseId.
   */
  public java.lang.String getCourseId() {
    java.lang.Object ref = courseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      courseId_ = s;
      return s;
    }
  }
  /**
   * <code>string course_id = 1;</code>
   * @return The bytes for courseId.
   */
  public com.google.protobuf.ByteString
      getCourseIdBytes() {
    java.lang.Object ref = courseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      courseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROF_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object profName_;
  /**
   * <code>string prof_name = 2;</code>
   * @return The profName.
   */
  public java.lang.String getProfName() {
    java.lang.Object ref = profName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      profName_ = s;
      return s;
    }
  }
  /**
   * <code>string prof_name = 2;</code>
   * @return The bytes for profName.
   */
  public com.google.protobuf.ByteString
      getProfNameBytes() {
    java.lang.Object ref = profName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COURSE_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object courseName_;
  /**
   * <code>string course_name = 3;</code>
   * @return The courseName.
   */
  public java.lang.String getCourseName() {
    java.lang.Object ref = courseName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      courseName_ = s;
      return s;
    }
  }
  /**
   * <code>string course_name = 3;</code>
   * @return The bytes for courseName.
   */
  public com.google.protobuf.ByteString
      getCourseNameBytes() {
    java.lang.Object ref = courseName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      courseName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREREQUISITE_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList prerequisite_;
  /**
   * <code>repeated string prerequisite = 4;</code>
   * @return A list containing the prerequisite.
   */
  public com.google.protobuf.ProtocolStringList
      getPrerequisiteList() {
    return prerequisite_;
  }
  /**
   * <code>repeated string prerequisite = 4;</code>
   * @return The count of prerequisite.
   */
  public int getPrerequisiteCount() {
    return prerequisite_.size();
  }
  /**
   * <code>repeated string prerequisite = 4;</code>
   * @param index The index of the element to return.
   * @return The prerequisite at the given index.
   */
  public java.lang.String getPrerequisite(int index) {
    return prerequisite_.get(index);
  }
  /**
   * <code>repeated string prerequisite = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the prerequisite at the given index.
   */
  public com.google.protobuf.ByteString
      getPrerequisiteBytes(int index) {
    return prerequisite_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCourseIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, courseId_);
    }
    if (!getProfNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, profName_);
    }
    if (!getCourseNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, courseName_);
    }
    for (int i = 0; i < prerequisite_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, prerequisite_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCourseIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, courseId_);
    }
    if (!getProfNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, profName_);
    }
    if (!getCourseNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, courseName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < prerequisite_.size(); i++) {
        dataSize += computeStringSizeNoTag(prerequisite_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPrerequisiteList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cluper.course_registration.Course)) {
      return super.equals(obj);
    }
    com.cluper.course_registration.Course other = (com.cluper.course_registration.Course) obj;

    if (!getCourseId()
        .equals(other.getCourseId())) return false;
    if (!getProfName()
        .equals(other.getProfName())) return false;
    if (!getCourseName()
        .equals(other.getCourseName())) return false;
    if (!getPrerequisiteList()
        .equals(other.getPrerequisiteList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COURSE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCourseId().hashCode();
    hash = (37 * hash) + PROF_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProfName().hashCode();
    hash = (37 * hash) + COURSE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCourseName().hashCode();
    if (getPrerequisiteCount() > 0) {
      hash = (37 * hash) + PREREQUISITE_FIELD_NUMBER;
      hash = (53 * hash) + getPrerequisiteList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cluper.course_registration.Course parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cluper.course_registration.Course parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cluper.course_registration.Course parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cluper.course_registration.Course parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cluper.course_registration.Course parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cluper.course_registration.Course parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cluper.course_registration.Course parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cluper.course_registration.Course parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cluper.course_registration.Course parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cluper.course_registration.Course parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cluper.course_registration.Course parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cluper.course_registration.Course parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cluper.course_registration.Course prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code university.Course}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:university.Course)
      com.cluper.course_registration.CourseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cluper.course_registration.University.internal_static_university_Course_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cluper.course_registration.University.internal_static_university_Course_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cluper.course_registration.Course.class, com.cluper.course_registration.Course.Builder.class);
    }

    // Construct using com.cluper.course_registration.Course.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      courseId_ = "";

      profName_ = "";

      courseName_ = "";

      prerequisite_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cluper.course_registration.University.internal_static_university_Course_descriptor;
    }

    @java.lang.Override
    public com.cluper.course_registration.Course getDefaultInstanceForType() {
      return com.cluper.course_registration.Course.getDefaultInstance();
    }

    @java.lang.Override
    public com.cluper.course_registration.Course build() {
      com.cluper.course_registration.Course result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cluper.course_registration.Course buildPartial() {
      com.cluper.course_registration.Course result = new com.cluper.course_registration.Course(this);
      int from_bitField0_ = bitField0_;
      result.courseId_ = courseId_;
      result.profName_ = profName_;
      result.courseName_ = courseName_;
      if (((bitField0_ & 0x00000001) != 0)) {
        prerequisite_ = prerequisite_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.prerequisite_ = prerequisite_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cluper.course_registration.Course) {
        return mergeFrom((com.cluper.course_registration.Course)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cluper.course_registration.Course other) {
      if (other == com.cluper.course_registration.Course.getDefaultInstance()) return this;
      if (!other.getCourseId().isEmpty()) {
        courseId_ = other.courseId_;
        onChanged();
      }
      if (!other.getProfName().isEmpty()) {
        profName_ = other.profName_;
        onChanged();
      }
      if (!other.getCourseName().isEmpty()) {
        courseName_ = other.courseName_;
        onChanged();
      }
      if (!other.prerequisite_.isEmpty()) {
        if (prerequisite_.isEmpty()) {
          prerequisite_ = other.prerequisite_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePrerequisiteIsMutable();
          prerequisite_.addAll(other.prerequisite_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cluper.course_registration.Course parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cluper.course_registration.Course) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object courseId_ = "";
    /**
     * <code>string course_id = 1;</code>
     * @return The courseId.
     */
    public java.lang.String getCourseId() {
      java.lang.Object ref = courseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string course_id = 1;</code>
     * @return The bytes for courseId.
     */
    public com.google.protobuf.ByteString
        getCourseIdBytes() {
      java.lang.Object ref = courseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string course_id = 1;</code>
     * @param value The courseId to set.
     * @return This builder for chaining.
     */
    public Builder setCourseId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      courseId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string course_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCourseId() {
      
      courseId_ = getDefaultInstance().getCourseId();
      onChanged();
      return this;
    }
    /**
     * <code>string course_id = 1;</code>
     * @param value The bytes for courseId to set.
     * @return This builder for chaining.
     */
    public Builder setCourseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      courseId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object profName_ = "";
    /**
     * <code>string prof_name = 2;</code>
     * @return The profName.
     */
    public java.lang.String getProfName() {
      java.lang.Object ref = profName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prof_name = 2;</code>
     * @return The bytes for profName.
     */
    public com.google.protobuf.ByteString
        getProfNameBytes() {
      java.lang.Object ref = profName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prof_name = 2;</code>
     * @param value The profName to set.
     * @return This builder for chaining.
     */
    public Builder setProfName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      profName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string prof_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfName() {
      
      profName_ = getDefaultInstance().getProfName();
      onChanged();
      return this;
    }
    /**
     * <code>string prof_name = 2;</code>
     * @param value The bytes for profName to set.
     * @return This builder for chaining.
     */
    public Builder setProfNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      profName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object courseName_ = "";
    /**
     * <code>string course_name = 3;</code>
     * @return The courseName.
     */
    public java.lang.String getCourseName() {
      java.lang.Object ref = courseName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string course_name = 3;</code>
     * @return The bytes for courseName.
     */
    public com.google.protobuf.ByteString
        getCourseNameBytes() {
      java.lang.Object ref = courseName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string course_name = 3;</code>
     * @param value The courseName to set.
     * @return This builder for chaining.
     */
    public Builder setCourseName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      courseName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string course_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCourseName() {
      
      courseName_ = getDefaultInstance().getCourseName();
      onChanged();
      return this;
    }
    /**
     * <code>string course_name = 3;</code>
     * @param value The bytes for courseName to set.
     * @return This builder for chaining.
     */
    public Builder setCourseNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      courseName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList prerequisite_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePrerequisiteIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        prerequisite_ = new com.google.protobuf.LazyStringArrayList(prerequisite_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @return A list containing the prerequisite.
     */
    public com.google.protobuf.ProtocolStringList
        getPrerequisiteList() {
      return prerequisite_.getUnmodifiableView();
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @return The count of prerequisite.
     */
    public int getPrerequisiteCount() {
      return prerequisite_.size();
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @param index The index of the element to return.
     * @return The prerequisite at the given index.
     */
    public java.lang.String getPrerequisite(int index) {
      return prerequisite_.get(index);
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the prerequisite at the given index.
     */
    public com.google.protobuf.ByteString
        getPrerequisiteBytes(int index) {
      return prerequisite_.getByteString(index);
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @param index The index to set the value at.
     * @param value The prerequisite to set.
     * @return This builder for chaining.
     */
    public Builder setPrerequisite(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePrerequisiteIsMutable();
      prerequisite_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @param value The prerequisite to add.
     * @return This builder for chaining.
     */
    public Builder addPrerequisite(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePrerequisiteIsMutable();
      prerequisite_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @param values The prerequisite to add.
     * @return This builder for chaining.
     */
    public Builder addAllPrerequisite(
        java.lang.Iterable<java.lang.String> values) {
      ensurePrerequisiteIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, prerequisite_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrerequisite() {
      prerequisite_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string prerequisite = 4;</code>
     * @param value The bytes of the prerequisite to add.
     * @return This builder for chaining.
     */
    public Builder addPrerequisiteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePrerequisiteIsMutable();
      prerequisite_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:university.Course)
  }

  // @@protoc_insertion_point(class_scope:university.Course)
  private static final com.cluper.course_registration.Course DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cluper.course_registration.Course();
  }

  public static com.cluper.course_registration.Course getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Course>
      PARSER = new com.google.protobuf.AbstractParser<Course>() {
    @java.lang.Override
    public Course parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Course(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Course> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Course> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cluper.course_registration.Course getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

