// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface GetAllCoursesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.GetAllCoursesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  java.util.List<com.cluper.course_registration.Course> 
      getCoursesList();
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  com.cluper.course_registration.Course getCourses(int index);
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  int getCoursesCount();
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  java.util.List<? extends com.cluper.course_registration.CourseOrBuilder> 
      getCoursesOrBuilderList();
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  com.cluper.course_registration.CourseOrBuilder getCoursesOrBuilder(
      int index);
}
