// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface GetAllStudentsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.GetAllStudentsRequest)
    com.google.protobuf.MessageOrBuilder {
}
