// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

/**
 * Protobuf type {@code university.GetAllCoursesResponse}
 */
public  final class GetAllCoursesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:university.GetAllCoursesResponse)
    GetAllCoursesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllCoursesResponse.newBuilder() to construct.
  private GetAllCoursesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllCoursesResponse() {
    courses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAllCoursesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAllCoursesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              courses_ = new java.util.ArrayList<com.cluper.course_registration.Course>();
              mutable_bitField0_ |= 0x00000001;
            }
            courses_.add(
                input.readMessage(com.cluper.course_registration.Course.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        courses_ = java.util.Collections.unmodifiableList(courses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cluper.course_registration.University.internal_static_university_GetAllCoursesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cluper.course_registration.University.internal_static_university_GetAllCoursesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cluper.course_registration.GetAllCoursesResponse.class, com.cluper.course_registration.GetAllCoursesResponse.Builder.class);
  }

  public static final int COURSES_FIELD_NUMBER = 1;
  private java.util.List<com.cluper.course_registration.Course> courses_;
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  public java.util.List<com.cluper.course_registration.Course> getCoursesList() {
    return courses_;
  }
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  public java.util.List<? extends com.cluper.course_registration.CourseOrBuilder> 
      getCoursesOrBuilderList() {
    return courses_;
  }
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  public int getCoursesCount() {
    return courses_.size();
  }
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  public com.cluper.course_registration.Course getCourses(int index) {
    return courses_.get(index);
  }
  /**
   * <code>repeated .university.Course courses = 1;</code>
   */
  public com.cluper.course_registration.CourseOrBuilder getCoursesOrBuilder(
      int index) {
    return courses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < courses_.size(); i++) {
      output.writeMessage(1, courses_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < courses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, courses_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cluper.course_registration.GetAllCoursesResponse)) {
      return super.equals(obj);
    }
    com.cluper.course_registration.GetAllCoursesResponse other = (com.cluper.course_registration.GetAllCoursesResponse) obj;

    if (!getCoursesList()
        .equals(other.getCoursesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoursesCount() > 0) {
      hash = (37 * hash) + COURSES_FIELD_NUMBER;
      hash = (53 * hash) + getCoursesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cluper.course_registration.GetAllCoursesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cluper.course_registration.GetAllCoursesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code university.GetAllCoursesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:university.GetAllCoursesResponse)
      com.cluper.course_registration.GetAllCoursesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cluper.course_registration.University.internal_static_university_GetAllCoursesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cluper.course_registration.University.internal_static_university_GetAllCoursesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cluper.course_registration.GetAllCoursesResponse.class, com.cluper.course_registration.GetAllCoursesResponse.Builder.class);
    }

    // Construct using com.cluper.course_registration.GetAllCoursesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCoursesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (coursesBuilder_ == null) {
        courses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        coursesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cluper.course_registration.University.internal_static_university_GetAllCoursesResponse_descriptor;
    }

    @java.lang.Override
    public com.cluper.course_registration.GetAllCoursesResponse getDefaultInstanceForType() {
      return com.cluper.course_registration.GetAllCoursesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.cluper.course_registration.GetAllCoursesResponse build() {
      com.cluper.course_registration.GetAllCoursesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cluper.course_registration.GetAllCoursesResponse buildPartial() {
      com.cluper.course_registration.GetAllCoursesResponse result = new com.cluper.course_registration.GetAllCoursesResponse(this);
      int from_bitField0_ = bitField0_;
      if (coursesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.courses_ = courses_;
      } else {
        result.courses_ = coursesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cluper.course_registration.GetAllCoursesResponse) {
        return mergeFrom((com.cluper.course_registration.GetAllCoursesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cluper.course_registration.GetAllCoursesResponse other) {
      if (other == com.cluper.course_registration.GetAllCoursesResponse.getDefaultInstance()) return this;
      if (coursesBuilder_ == null) {
        if (!other.courses_.isEmpty()) {
          if (courses_.isEmpty()) {
            courses_ = other.courses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCoursesIsMutable();
            courses_.addAll(other.courses_);
          }
          onChanged();
        }
      } else {
        if (!other.courses_.isEmpty()) {
          if (coursesBuilder_.isEmpty()) {
            coursesBuilder_.dispose();
            coursesBuilder_ = null;
            courses_ = other.courses_;
            bitField0_ = (bitField0_ & ~0x00000001);
            coursesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCoursesFieldBuilder() : null;
          } else {
            coursesBuilder_.addAllMessages(other.courses_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cluper.course_registration.GetAllCoursesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cluper.course_registration.GetAllCoursesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.cluper.course_registration.Course> courses_ =
      java.util.Collections.emptyList();
    private void ensureCoursesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        courses_ = new java.util.ArrayList<com.cluper.course_registration.Course>(courses_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cluper.course_registration.Course, com.cluper.course_registration.Course.Builder, com.cluper.course_registration.CourseOrBuilder> coursesBuilder_;

    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public java.util.List<com.cluper.course_registration.Course> getCoursesList() {
      if (coursesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(courses_);
      } else {
        return coursesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public int getCoursesCount() {
      if (coursesBuilder_ == null) {
        return courses_.size();
      } else {
        return coursesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public com.cluper.course_registration.Course getCourses(int index) {
      if (coursesBuilder_ == null) {
        return courses_.get(index);
      } else {
        return coursesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder setCourses(
        int index, com.cluper.course_registration.Course value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.set(index, value);
        onChanged();
      } else {
        coursesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder setCourses(
        int index, com.cluper.course_registration.Course.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.set(index, builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder addCourses(com.cluper.course_registration.Course value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.add(value);
        onChanged();
      } else {
        coursesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder addCourses(
        int index, com.cluper.course_registration.Course value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.add(index, value);
        onChanged();
      } else {
        coursesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder addCourses(
        com.cluper.course_registration.Course.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.add(builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder addCourses(
        int index, com.cluper.course_registration.Course.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.add(index, builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder addAllCourses(
        java.lang.Iterable<? extends com.cluper.course_registration.Course> values) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, courses_);
        onChanged();
      } else {
        coursesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder clearCourses() {
      if (coursesBuilder_ == null) {
        courses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        coursesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public Builder removeCourses(int index) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.remove(index);
        onChanged();
      } else {
        coursesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public com.cluper.course_registration.Course.Builder getCoursesBuilder(
        int index) {
      return getCoursesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public com.cluper.course_registration.CourseOrBuilder getCoursesOrBuilder(
        int index) {
      if (coursesBuilder_ == null) {
        return courses_.get(index);  } else {
        return coursesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public java.util.List<? extends com.cluper.course_registration.CourseOrBuilder> 
         getCoursesOrBuilderList() {
      if (coursesBuilder_ != null) {
        return coursesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(courses_);
      }
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public com.cluper.course_registration.Course.Builder addCoursesBuilder() {
      return getCoursesFieldBuilder().addBuilder(
          com.cluper.course_registration.Course.getDefaultInstance());
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public com.cluper.course_registration.Course.Builder addCoursesBuilder(
        int index) {
      return getCoursesFieldBuilder().addBuilder(
          index, com.cluper.course_registration.Course.getDefaultInstance());
    }
    /**
     * <code>repeated .university.Course courses = 1;</code>
     */
    public java.util.List<com.cluper.course_registration.Course.Builder> 
         getCoursesBuilderList() {
      return getCoursesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cluper.course_registration.Course, com.cluper.course_registration.Course.Builder, com.cluper.course_registration.CourseOrBuilder> 
        getCoursesFieldBuilder() {
      if (coursesBuilder_ == null) {
        coursesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cluper.course_registration.Course, com.cluper.course_registration.Course.Builder, com.cluper.course_registration.CourseOrBuilder>(
                courses_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        courses_ = null;
      }
      return coursesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:university.GetAllCoursesResponse)
  }

  // @@protoc_insertion_point(class_scope:university.GetAllCoursesResponse)
  private static final com.cluper.course_registration.GetAllCoursesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cluper.course_registration.GetAllCoursesResponse();
  }

  public static com.cluper.course_registration.GetAllCoursesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllCoursesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllCoursesResponse>() {
    @java.lang.Override
    public GetAllCoursesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAllCoursesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAllCoursesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllCoursesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cluper.course_registration.GetAllCoursesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

