// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .university.Student students = 1;</code>
   */
  java.util.List<com.cluper.course_registration.Student> 
      getStudentsList();
  /**
   * <code>repeated .university.Student students = 1;</code>
   */
  com.cluper.course_registration.Student getStudents(int index);
  /**
   * <code>repeated .university.Student students = 1;</code>
   */
  int getStudentsCount();
  /**
   * <code>repeated .university.Student students = 1;</code>
   */
  java.util.List<? extends com.cluper.course_registration.StudentOrBuilder> 
      getStudentsOrBuilderList();
  /**
   * <code>repeated .university.Student students = 1;</code>
   */
  com.cluper.course_registration.StudentOrBuilder getStudentsOrBuilder(
      int index);
}
