// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public final class University {
  private University() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_GetAllStudentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_GetAllStudentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_GetAllStudentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_GetAllStudentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_AddStudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_AddStudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_AddStudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_AddStudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_DeleteStudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_DeleteStudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_DeleteStudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_DeleteStudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_GetAllCoursesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_GetAllCoursesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_GetAllCoursesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_GetAllCoursesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_GetReservedCoursesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_GetReservedCoursesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_GetReservedCoursesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_GetReservedCoursesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_AddCourseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_AddCourseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_AddCourseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_AddCourseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_DeleteCourseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_DeleteCourseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_DeleteCourseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_DeleteCourseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_MakeReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_MakeReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_MakeReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_MakeReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_CancelReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_CancelReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_CancelReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_CancelReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_Students_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_Students_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_Course_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_Course_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_university_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_university_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020university.proto\022\nuniversity\"\027\n\025GetAll" +
      "StudentsRequest\"?\n\026GetAllStudentsRespons" +
      "e\022%\n\010students\030\001 \003(\0132\023.university.Student" +
      "\"9\n\021AddStudentRequest\022$\n\007student\030\001 \001(\0132\023" +
      ".university.Student\"K\n\022AddStudentRespons" +
      "e\0225\n\020response_message\030\001 \001(\0132\033.university" +
      ".ResponseMessage\"*\n\024DeleteStudentRequest" +
      "\022\022\n\nstudent_id\030\001 \001(\t\"N\n\025DeleteStudentRes" +
      "ponse\0225\n\020response_message\030\001 \001(\0132\033.univer" +
      "sity.ResponseMessage\"\026\n\024GetAllCoursesReq" +
      "uest\"<\n\025GetAllCoursesResponse\022#\n\007courses" +
      "\030\001 \003(\0132\022.university.Course\"/\n\031GetReserve" +
      "dCoursesRequest\022\022\n\nstudent_id\030\001 \001(\t\"A\n\032G" +
      "etReservedCoursesResponse\022#\n\007courses\030\001 \003" +
      "(\0132\022.university.Course\"6\n\020AddCourseReque" +
      "st\022\"\n\006course\030\001 \001(\0132\022.university.Course\"J" +
      "\n\021AddCourseResponse\0225\n\020response_message\030" +
      "\001 \001(\0132\033.university.ResponseMessage\"(\n\023De" +
      "leteCourseRequest\022\021\n\tcourse_id\030\001 \001(\t\"M\n\024" +
      "DeleteCourseResponse\0225\n\020response_message" +
      "\030\001 \001(\0132\033.university.ResponseMessage\"F\n\026M" +
      "akeReservationRequest\022,\n\013reservation\030\001 \001" +
      "(\0132\027.university.Reservation\"P\n\027MakeReser" +
      "vationResponse\0225\n\020response_message\030\001 \001(\013" +
      "2\033.university.ResponseMessage\"H\n\030CancelR" +
      "eservationRequest\022,\n\013reservation\030\001 \001(\0132\027" +
      ".university.Reservation\"R\n\031CancelReserva" +
      "tionResponse\0225\n\020response_message\030\001 \001(\0132\033" +
      ".university.ResponseMessage\"0\n\010Students\022" +
      "$\n\007student\030\001 \003(\0132\023.university.Student\"k\n" +
      "\007Student\022\022\n\nstudent_id\030\001 \001(\t\022\021\n\tlast_nam" +
      "e\030\002 \001(\t\022\022\n\nfirst_name\030\003 \001(\t\022\022\n\ndepartmen" +
      "t\030\004 \001(\t\022\021\n\tcourse_id\030\005 \003(\t\"Y\n\006Course\022\021\n\t" +
      "course_id\030\001 \001(\t\022\021\n\tprof_name\030\002 \001(\t\022\023\n\013co" +
      "urse_name\030\003 \001(\t\022\024\n\014prerequisite\030\004 \003(\t\"4\n" +
      "\013Reservation\022\022\n\nstudent_id\030\001 \001(\t\022\021\n\tcour" +
      "se_id\030\002 \003(\t\"3\n\017ResponseMessage\022\017\n\007succes" +
      "s\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\246\006\n\022Reservation" +
      "Service\022W\n\016GetAllStudents\022!.university.G" +
      "etAllStudentsRequest\032\".university.GetAll" +
      "StudentsResponse\022K\n\nAddStudent\022\035.univers" +
      "ity.AddStudentRequest\032\036.university.AddSt" +
      "udentResponse\022T\n\rDeleteStudent\022 .univers" +
      "ity.DeleteStudentRequest\032!.university.De" +
      "leteStudentResponse\022T\n\rGetAllCourses\022 .u" +
      "niversity.GetAllCoursesRequest\032!.univers" +
      "ity.GetAllCoursesResponse\022c\n\022GetReserved" +
      "Courses\022%.university.GetReservedCoursesR" +
      "equest\032&.university.GetReservedCoursesRe" +
      "sponse\022H\n\tAddCourse\022\034.university.AddCour" +
      "seRequest\032\035.university.AddCourseResponse" +
      "\022Q\n\014DeleteCourse\022\037.university.DeleteCour" +
      "seRequest\032 .university.DeleteCourseRespo" +
      "nse\022Z\n\017MakeReservation\022\".university.Make" +
      "ReservationRequest\032#.university.MakeRese" +
      "rvationResponse\022`\n\021CancelReservation\022$.u" +
      "niversity.CancelReservationRequest\032%.uni" +
      "versity.CancelReservationResponseB.\n\036com" +
      ".cluper.course_registrationB\nUniversityP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_university_GetAllStudentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_university_GetAllStudentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_GetAllStudentsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_university_GetAllStudentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_university_GetAllStudentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_GetAllStudentsResponse_descriptor,
        new java.lang.String[] { "Students", });
    internal_static_university_AddStudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_university_AddStudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_AddStudentRequest_descriptor,
        new java.lang.String[] { "Student", });
    internal_static_university_AddStudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_university_AddStudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_AddStudentResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_university_DeleteStudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_university_DeleteStudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_DeleteStudentRequest_descriptor,
        new java.lang.String[] { "StudentId", });
    internal_static_university_DeleteStudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_university_DeleteStudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_DeleteStudentResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_university_GetAllCoursesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_university_GetAllCoursesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_GetAllCoursesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_university_GetAllCoursesResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_university_GetAllCoursesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_GetAllCoursesResponse_descriptor,
        new java.lang.String[] { "Courses", });
    internal_static_university_GetReservedCoursesRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_university_GetReservedCoursesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_GetReservedCoursesRequest_descriptor,
        new java.lang.String[] { "StudentId", });
    internal_static_university_GetReservedCoursesResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_university_GetReservedCoursesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_GetReservedCoursesResponse_descriptor,
        new java.lang.String[] { "Courses", });
    internal_static_university_AddCourseRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_university_AddCourseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_AddCourseRequest_descriptor,
        new java.lang.String[] { "Course", });
    internal_static_university_AddCourseResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_university_AddCourseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_AddCourseResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_university_DeleteCourseRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_university_DeleteCourseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_DeleteCourseRequest_descriptor,
        new java.lang.String[] { "CourseId", });
    internal_static_university_DeleteCourseResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_university_DeleteCourseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_DeleteCourseResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_university_MakeReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_university_MakeReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_MakeReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_university_MakeReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_university_MakeReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_MakeReservationResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_university_CancelReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_university_CancelReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_CancelReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_university_CancelReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_university_CancelReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_CancelReservationResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
    internal_static_university_Students_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_university_Students_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_Students_descriptor,
        new java.lang.String[] { "Student", });
    internal_static_university_Student_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_university_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_Student_descriptor,
        new java.lang.String[] { "StudentId", "LastName", "FirstName", "Department", "CourseId", });
    internal_static_university_Course_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_university_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_Course_descriptor,
        new java.lang.String[] { "CourseId", "ProfName", "CourseName", "Prerequisite", });
    internal_static_university_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_university_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_Reservation_descriptor,
        new java.lang.String[] { "StudentId", "CourseId", });
    internal_static_university_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_university_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_university_ResponseMessage_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
