// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface AddCourseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.AddCourseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.university.ResponseMessage response_message = 1;</code>
   * @return Whether the responseMessage field is set.
   */
  boolean hasResponseMessage();
  /**
   * <code>.university.ResponseMessage response_message = 1;</code>
   * @return The responseMessage.
   */
  com.cluper.course_registration.ResponseMessage getResponseMessage();
  /**
   * <code>.university.ResponseMessage response_message = 1;</code>
   */
  com.cluper.course_registration.ResponseMessageOrBuilder getResponseMessageOrBuilder();
}
