// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface CoursesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.Courses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .university.Course course = 1;</code>
   */
  java.util.List<com.cluper.course_registration.Course> 
      getCourseList();
  /**
   * <code>repeated .university.Course course = 1;</code>
   */
  com.cluper.course_registration.Course getCourse(int index);
  /**
   * <code>repeated .university.Course course = 1;</code>
   */
  int getCourseCount();
  /**
   * <code>repeated .university.Course course = 1;</code>
   */
  java.util.List<? extends com.cluper.course_registration.CourseOrBuilder> 
      getCourseOrBuilderList();
  /**
   * <code>repeated .university.Course course = 1;</code>
   */
  com.cluper.course_registration.CourseOrBuilder getCourseOrBuilder(
      int index);
}
