// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string course_id = 1;</code>
   * @return The courseId.
   */
  java.lang.String getCourseId();
  /**
   * <code>string course_id = 1;</code>
   * @return The bytes for courseId.
   */
  com.google.protobuf.ByteString
      getCourseIdBytes();

  /**
   * <code>string prof_name = 2;</code>
   * @return The profName.
   */
  java.lang.String getProfName();
  /**
   * <code>string prof_name = 2;</code>
   * @return The bytes for profName.
   */
  com.google.protobuf.ByteString
      getProfNameBytes();

  /**
   * <code>string course_name = 3;</code>
   * @return The courseName.
   */
  java.lang.String getCourseName();
  /**
   * <code>string course_name = 3;</code>
   * @return The bytes for courseName.
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();
}
