// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string course_id = 1;</code>
   * @return The courseId.
   */
  java.lang.String getCourseId();
  /**
   * <code>string course_id = 1;</code>
   * @return The bytes for courseId.
   */
  com.google.protobuf.ByteString
      getCourseIdBytes();

  /**
   * <code>string prof_name = 2;</code>
   * @return The profName.
   */
  java.lang.String getProfName();
  /**
   * <code>string prof_name = 2;</code>
   * @return The bytes for profName.
   */
  com.google.protobuf.ByteString
      getProfNameBytes();

  /**
   * <code>string course_name = 3;</code>
   * @return The courseName.
   */
  java.lang.String getCourseName();
  /**
   * <code>string course_name = 3;</code>
   * @return The bytes for courseName.
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();

  /**
   * <code>repeated string prerequisite = 4;</code>
   * @return A list containing the prerequisite.
   */
  java.util.List<java.lang.String>
      getPrerequisiteList();
  /**
   * <code>repeated string prerequisite = 4;</code>
   * @return The count of prerequisite.
   */
  int getPrerequisiteCount();
  /**
   * <code>repeated string prerequisite = 4;</code>
   * @param index The index of the element to return.
   * @return The prerequisite at the given index.
   */
  java.lang.String getPrerequisite(int index);
  /**
   * <code>repeated string prerequisite = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the prerequisite at the given index.
   */
  com.google.protobuf.ByteString
      getPrerequisiteBytes(int index);
}
