// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface GetAllCoursesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.GetAllCoursesRequest)
    com.google.protobuf.MessageOrBuilder {
}
