// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface MakeReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.MakeReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.university.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.university.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  com.cluper.course_registration.Reservation getReservation();
  /**
   * <code>.university.Reservation reservation = 1;</code>
   */
  com.cluper.course_registration.ReservationOrBuilder getReservationOrBuilder();
}
