// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: university.proto

package com.cluper.course_registration;

public interface StudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:university.Students)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .university.Student student = 1;</code>
   */
  java.util.List<com.cluper.course_registration.Student> 
      getStudentList();
  /**
   * <code>repeated .university.Student student = 1;</code>
   */
  com.cluper.course_registration.Student getStudent(int index);
  /**
   * <code>repeated .university.Student student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .university.Student student = 1;</code>
   */
  java.util.List<? extends com.cluper.course_registration.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .university.Student student = 1;</code>
   */
  com.cluper.course_registration.StudentOrBuilder getStudentOrBuilder(
      int index);
}
